spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bliushtein_yp_sprint4_test_db
  sql:
    init:
      data-locations: optional:classpath:/db/init_test_data_for_post_repository.sql, optional:classpath:/db/cleanup_test_data_for_file_storage.sql